### ISSUE TITLE
feasibility-research(runtime): Support kubernetes as the backend vendor

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#179]
- [x] #92 
- [x] #939
  - [x]  #957 
- [ ] https://github.com/tensorchord/envd/issues/530
- [ ] https://github.com/tensorchord/envd/issues/101
- [x] https://github.com/tensorchord/envd/issues/958

**Comment by gaocegege** [comment]
> I think we could not mount local dir to container in k8s cluster directly, how about we spawn a rsyncd inside the container, and sync working dir by using rsync?

Yep we may need https://syncthing.net/

**Comment by gaocegege** [comment]
#dibs
/assign

**Comment by LeonardAukea** [comment]
> > working dir mount
> 
> I think we could not mount local dir to container in k8s cluster directly, how about we spawn a rsyncd inside the container, and sync working dir by using rsync?
> 
> > We cannot forward port to localhost (or maybe we can via kubectl port forward?)
> 
> This module https://pkg.go.dev/k8s.io/client-go/tools/portforward might be helpful.

Maybe this is relevant to the discussion. @gaocegege It also utilises syncthing   https://github.com/ksync/ksync/blob/master/docs/architecture.md

**Comment by gaocegege** [comment]
> > > working dir mount
> > 
> > 
> > I think we could not mount local dir to container in k8s cluster directly, how about we spawn a rsyncd inside the container, and sync working dir by using rsync?
> > > We cannot forward port to localhost (or maybe we can via kubectl port forward?)
> > 
> > 
> > This module https://pkg.go.dev/k8s.io/client-go/tools/portforward might be helpful.
> 
> Maybe this is relevant to the discussion. @gaocegege It also utilises syncthing https://github.com/ksync/ksync/blob/master/docs/architecture.md

Thanks for the info! it seems like a clean wrapper of sycthing.
