### ISSUE TITLE
chore(milestone): Setup 0.1.0 milestone

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#214]
Features:

- [x] https://github.com/tensorchord/envd/issues/216
- [ ] https://github.com/tensorchord/envd/issues/213
- [x] https://github.com/tensorchord/envd/issues/209
- [x] https://github.com/tensorchord/envd/issues/192
- [ ] https://github.com/tensorchord/envd/issues/179
- [ ] https://github.com/tensorchord/envd/issues/218
- [x] https://github.com/tensorchord/envd/issues/149
- [ ] https://github.com/tensorchord/envd/issues/128
- [ ] https://github.com/tensorchord/envd/issues/114
- [ ] https://github.com/tensorchord/envd/issues/92
- [x] https://github.com/tensorchord/envd/issues/185

Bug fixes:

- [x] https://github.com/tensorchord/envd/issues/183

**Comment by gaocegege** [comment]
I am closing it since we already open-sourced the project. Let's make a roadmap in the repo instead of the issue.
