### ISSUE TITLE
feat(lang): Support Source Code Management

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#6]
## Description

Code may be one of the first-class objects in the build language. The code will exist in the resulting container and users develop models and update them. After the code is changed, you can commit and push to remote.

```
CODE:
    GIT SSH /root/.ssh/github-key
    GIT LOCAL $HOME/private-repo
    GIT CLONE git@github.com/tensorchord/private-repo.git
    # TODO: Support branch and commit
```

## Feature lists

- [x] #23
- [ ] Support public repos
- [ ] SSH keys to support private repos
- [ ] Cache if the repo exists locally
